plugins {
	id "net.fabricmc.fabric-loom" version "${loom_version}"
}

version = project.mod_version
group = project.maven_group
def expandedVersion = version.toString()

base {
	archivesName = "MidnightClient"
}

loom {
	splitEnvironmentSourceSets()

	mods {
		hackmc {
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation project(":screenapi")
	include project(":screenapi")
}

processResources {
	inputs.property "version", expandedVersion
	filesMatching("fabric.mod.json") {
		expand "version": expandedVersion
	}
}

processClientResources {
	inputs.property "version", expandedVersion
	filesMatching("fabric.mod.json") {
		expand "version": expandedVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
